Repository ansible/creator-ee, pull requests merged in 2022-03, with the labels that each got.

#23 Add molecule-podman driver
  _build/requirements.txt
  _build/requirements.yml
Labels: enhancement

#30 Added missing shared pipelines
  .github/CODEOWNERS
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
Labels: skip-changelog

#22 Add docker molecule driver
  _build/requirements.txt
  _build/requirements.yml
Labels: enhancement

#24 Add molecule-containers driver
  _build/requirements.txt
Labels: enhancement

#27 Add molecule-openstack driver
  _build/requirements.txt
Labels: enhancement

#32 Fix dependabot configuration
  .github/dependabot.yml
Labels: skip-changelog

#29 Refactor tox.ini file
  tox.ini
Labels: skip-changelog

#34 Enable prettier
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .prettierrc
  README.md
Labels: skip-changelog

#35 Fix release pipeline to trigger on published event
  .github/workflows/release.yml
Labels: bug, skip-changelog

#37 Add podman and docker binaries
  Containerfile
  _build/bindep.txt
  execution-environment.yml
Labels: bug

#39 Add safety check of image size
  tox.ini
Labels: skip-changelog

#42 Bump ansible-lint to 6.0.1
  _build/requirements.txt
Labels: enhancement

#43 Ensure all direct dependencies are pinned
  _build/requirements.txt
Labels: bug

#46 Use ansible-lint 6.0.2
  _build/requirements.txt
Labels: bug
