Repository ansible/creator-ee, pull requests merged in 2022-11, with the labels that each got.

#212 Fix readonly UID warning
  _build/entrypoint.sh
Labels: bug

#213 Avoid using -t with podman run
  _build/validate
Labels: skip-changelog

#214 Use ansible-lint 6.8.6
  _build/requirements.in
  _build/requirements.txt
Labels: bug

#223 Use fedora-minimal:37 as base image
  _build/validate
  base/Containerfile
Labels: bug

#225 Specifically install python
  base/Containerfile
Labels: skip-changelog

#227 Switch to py311
  .github/workflows/release.yml
  .github/workflows/task.yml
  .github/workflows/update-base.yml
  .pre-commit-config.yaml
  Taskfile.yml
  _build/requirements.txt
  _build/runtime.txt
Labels: bug

#228 Remove dnf cache from image
  Taskfile.yml
  base/Containerfile
Labels: bug

#230 Add python3-markupsafe to base image
  .pre-commit-config.yaml
  _build/requirements.txt
  base/Containerfile
Labels: bug

#233 [enhancement] Include jmespath to enable json_query
  _build/requirements.in
  _build/requirements.txt
Labels: enhancement

#236 Update ansible-lint to 6.8.7
  _build/requirements.txt
Labels: bug
