Repository ansible/creator-ee, pull requests merged in 2022-10, with the labels that each got.

#143 Specify paramiko 2.11.0
  _build/requirements.txt
Labels: bug

#144 Update ansible-lint to 6.8.0b3
  _build/requirements.txt
Labels: enhancement

#147 Include paramiko
  _build/requirements.in
  _build/requirements.txt
Labels: bug

#149 Replace ansible-builder with plain container building
  .github/workflows/tox.yml
  Containerfile
  tox.ini
Labels: bug

#150 Enable multi-platform container building
  .github/workflows/tox.yml
  Containerfile
  tox.ini
Labels: bug

#152 Temporary empty container
  tox.ini
Labels: bug

#153 Temporary empty container
  Containerfile
Labels: bug, skip-changelog

#154 Replace tox with taskfile
  .github/workflows/release.yml
  .github/workflows/task.yml
  .gitignore
  Taskfile.yml
  _build/dirty.sh
  _build/test-setup.sh
  tox.ini
Labels: skip-changelog

#155 Ensure release uses multi-arch
  .github/workflows/release.yml
Labels: bug, skip-changelog

#156 Add registry logins
  .github/workflows/release.yml
Labels: bug, skip-changelog

#157 Allow release pipeline to push
  .github/workflows/release.yml
Labels: skip-changelog

#158 Prevent publishing when tag is missing
  Taskfile.yml
Labels: skip-changelog

#159 Push latest tag on release
  Taskfile.yml
Labels: skip-changelog

#160 Restore container build steps
  .github/workflows/release.yml
  .github/workflows/task.yml
  Containerfile
  Taskfile.yml
Labels: skip-changelog

#161 Add dependency update task
  .pre-commit-config.yaml
  Taskfile.yml
  _build/requirements.in
  _build/requirements.txt
  _build/test-setup.sh
Labels: skip-changelog

#162 Remove leftovers
  Dockerfile
  tox.ini
Labels: skip-changelog

#164 Fixed pushing of tags
  Taskfile.yml
Labels: skip-changelog

#167 Allow installing pre-releases for our own packages
  .pre-commit-config.yaml
  _build/requirements.in
Labels: skip-changelog

#168 Configure dependabot to use py3.10
  _build/runtime.txt
Labels: skip-changelog

#169 Use ansible-core 2.14.0b2
  .github/workflows/update-base.yml
  _build/requirements.txt
Labels: enhancement

#171 Add dumb-init to base image
  .github/workflows/task.yml
  .github/workflows/update-base.yml
  Taskfile.yml
  base/Containerfile
Labels: bug

#175 Add dumb-init to base image
  Containerfile
  Taskfile.yml
  _build/entrypoint.sh
  _build/requirements.in
  _build/requirements.txt
  base/Containerfile
Labels: bug

#179 Add an EE label
  Containerfile
Labels: enhancement

#181 Install requirements.yml
  Containerfile
Labels: bug

#186 Add collection publish script
  _build/devtools-publish
Labels: enhancement

#187 Include devtools-publish into container
  Containerfile
Labels: bug

#188 Update README file
  README.md
Labels: bug

#190 Added non-pure python packages to unsafe list
  .pre-commit-config.yaml
  _build/requirements.txt
Labels: bug

#192 Update molecule to 4.0.3
  _build/requirements.txt
Labels: bug

#195 Fix permissions on build image
  Containerfile
  Taskfile.yml
  _build/validate
Labels: bug

#196 Enable shellcheck
  .pre-commit-config.yaml
  _build/entrypoint.sh
  _build/validate
Labels: bug, feature

#197 More fixes to entrypoint
  .pre-commit-config.yaml
  Taskfile.yml
  _build/entrypoint.sh
  _build/validate
Labels: bug

#199 Ensure default shell is bash
  Containerfile
  _build/shells
Labels: bug

#201 Install collections from local
  .github/workflows/task.yml
  .gitignore
  Containerfile
  Taskfile.yml
  _build/test-setup.sh
Labels: bug

#203 Replace docker container shellcheck with python based hook
  .pre-commit-config.yaml
Labels: skip-changelog

#205 Update ansible-lint to 6.8.4
  _build/requirements.txt
Labels: bug
